circe-pkg.el
The package name must be a symbol, and not a string.
=> Fix fixed dependency syntax

scripts/compile
As written, the script fails with the following error:
```
==> scripts/compile
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```
=> scripts/compile: fix `find` command for OSX

circe-pkg.el
Enable Emacs to understand package's homepage, for example, via
'C-h P circe`.
Without the fix, the homepage can't be displayed correctly:
(tested on Emacs 25.0.50.5, built from git repo recently)
=> Add URL meta-data to package file

circe.el
Otherwise, the byte-compiler mistakes its first use for a function
reference and does not correctly expand it in `circe-reconnect.
Fix issue #223
=> Define macro `with-circe-server-buffer` before it's first used

lui.el
As discussed in #236, here are two dynamic variables that affect the TIME and ZONE arguments of `format-time-string` in `lui-time-stamp`. I hope this is what you had in mind as well. I tried to use descriptive names and provide descriptive docstrings, if I need to rename/reword anything please let me know.
I've tried out binding `lui-time-stamp-time` to the value we get from the external service and it works like a charm. I've tested setting `lui-time-stamp-zone` to a different timezone and all the time stamps changed accordingly.
I didn't find any tests for `lui-time-stamp` or `lui-insert` (or any lui functions, really), in `tests/`, so I didn't write any either.
Please let me know what you think.
=> Add time and zone arguments for lui-time-stamp

lui.el
I've tested this briefly with both options as given in the customization variable.  There's a few open questions for me though:
- Does this feature warrant an extra mention in the file header?
- Is this feature best kept in `lui-irc-colors.el`?
- Finally, shall I mention it in the wiki?  I personally wouldn't think of scouring `lui-irc-colors.el` for such a feature...
=> Add inline markup support

circe.el, lui-irc-colors.el
Now they depend on background, and should be legible by default.
The [contrast ratio](http://webaim.org/resources/contrastchecker/) of at least 7 is preserved for adwaita (dark-on-light, background color #ededed) and wombat (light-on-dark, #242424; actually used #303030 to cover more themes) color themes. Tried to not affect `(type tty)`.
The bluish theme is preserved, though not as blue as before: blue is pretty dark by itself, so it limits the options for a light-on-dark theme.
=> Changed some of the default faces

irc.el, tests/test-irc.el
Slack IRC gateway sends following messages:
":irc.tinyspeck.com 333 nick #channel  0"
Note the double-space at the end -- the `setter` argument is
missing (see `circe-display-333`).
According to RFC2812, section 2.3:
The prefix, command, and all parameters are separated by one ASCII
space character (0x20) each.
Could be relevant to GitHub issue #148.
=> Fix irc--parse to work with Slack gateway

lui-track-bar.el
Currently the display of track bar is sub-optimal -- it is fixed width
and does not work well with time-stamps.
Instead of using a set width of space with strike-through face, use
background color on a newline -- this way Emacs fills the whole buffer
width with the face's background color.  The height of the line can be
customized by setting the face height value to a fraction.  This trick
also works on TTY.
A note should probably be added to changelog to avoid user confusion
when they discover the track bar is no longer visible.
=> Improve track bar appearance

lui.el
I don't know if there is a specific reason to put the text for the time stamp margin at the end of the line, so I only changed it for my specific use case. Please let me know what you think.
---
Put the time stamp display text at the beginning of the line when
`lui-time-stamp-position` is either left-margin or right-margin and
`lui-fill-type` is nil.
When `lui-fill-type` has a value of nil, `visual-line-mode` is enabled
and the `lui-time-stamp-position` is either left-margin or
right-margin the time stamp appears in the margin of the last line of
the message. For all other situations it appears in the margin of the
first line of the message.
=> Fix margin time stamp position

circe.el, tests/test-circe.el
test in test-circe.el checks specifically that a message-text of nil is translated to (and subsequently passed to circe-display as) "unknown seconds"
Couldn't get cask set up to test this, so I tested it by buttercup-run-discover. If someone can do the cask check and confirm it works on all supported versions, that'd be great.
fixes #296
=> add when text check, add CTCP PING test

README.md
If you don't like the wording, you could just change it. I don't mind if you accept this pull-request but it'd be good to name GnuTLS as run-time dependency for TLS connections.
=> At installation, name GnuTLS as dependency for TLS connections

README.md, circe-display-images.el
This module enables Circe to download and display images in the
channel buffer. Users are also able to toggle images off.
=> Add Circe Display Images module

lui.el
`lui-insert-with-text-properties` add text-property `'lui-saved-properties` to whole buffer.
[`(add-text-property ...)`](https://github.com/jorgenschaefer/circe/blob/master/lui.el#L1003) is executed after [`(widen)`](https://github.com/jorgenschaefer/circe/blob/master/lui.el#L995), `(point-min)` and `(point-max)` return whole buffer.
I move `(add-text-property ...)` before `(widen)` .
=> fix lui-saved-text-properties added whole buffer

circe-color-nicks.el, tests/test-circe-color-nicks.el
If a nick hasn't been colored yet (perhaps they haven't spoken yet), they won't have an entry in circe-nick-color-mapping. If they don't have an entry, `circe-nick-color-nick-list` will not return them in the list. This results in a couple of nicks not being colored if they haven't spoken yet or if the table is flushed.
I'm not sure if this will have an adverse effect on performance, but I don't think it will because the `circe-nick-color-nick-list` is doing a bunch of additional processing that was removed as well. I don't know if it's enough to compensate for the extra time spent in `regexp-opt` (I assume that will happen), but from using this for a couple days, I don't see any huge differences.
This removes all usages of `circe-nick-color-nick-list` let me know if it's ok to just …
=> Fix nick colors if nick hasn't spoken yet

circe.el, irc.el, tests/test-irc.el
This PR adds a stats command to circe. In order to avoid combinining the multiple args (eg: `/stats p adams.freenode.net`), I split the incoming argument string. Let me know if you think there's a cleaner way to do this, I'm not sure what exactly the convention is here.
I could also use `irc-send-raw`, but that seems more hacky to me. 
Also see [the stats command](https://en.wikipedia.org/wiki/List_of_Internet_Relay_Chat_commands#STATS) for sytax.
I'm adding this because in the topic of `#freenode`, it says:
```
*** Topic for #freenode: Welcome to #freenode | Feel free to message
staff at any time. You can find us using /stats p (shows
immediately-available staff) or /who freenode/staff/* (shows all
staff) |
```
which dosen't work in circe, as there is no stats command.
Let me know if …
=> Add a stats command to circe

lui-autopaste.el
It seems ptpb.pw died on us: https://github.com/ptpb/pb/issues/246
This replaces its function with sprunge.us, a pastebin service that's very similar to ix.io. Let me know if you think I should do something to help with migration for users who decided to opt into ptpb.pw, like throwing an error telling them to migrate.
=> Replace ptpb.pw with sprunge.us

circe.el
Apply same fix as in df9a1dc.
While here fix that after /GQUIT circe would immediately try to reconnect.
=> fix for GH-282: /GQUIT does nothing

circe-display-images.el, circe.el, lui.el
This replaces some deprecated symbols with their replacements.
There's another one but that requires emacs 27.1:
```
circe-display-images.el:127:14: Warning: ‘url-get-url-at-point’ is an obsolete
function (as of 27.1); use ‘thing-at-point-url-at-point’ instead.
```
=> Dont use deprecated variables

tracking.el
By limiting shortened buffers to those actually using tracking.el or
lui, we can gain a substantial performance improvement for tracking
said buffers (when shortening).
Alternatively, we can add a variable to only shorten currently tracked
buffers (ie: tracking-buffers), which will be even faster.
I actually prefer shortening only the currently tracked buffers even if it
leads to non-deterministic shortening. Do you like that solution more?
See: #286, #346, #344
For me:
```
(benchmark-run 1000 (tracking-shorten nil))
tracking-shorten-modes: t
(8.734324133 8 4.102178583008936)
tracking-shorten-modes: (circe-channel-mode)
(2.075575641 2 1.031831622007303)
```
As you can see, we still have a way to go on this function (and others in the critical path), but it's a start. Unfortunately, it all …
=> Add `tracking-shorten-modes' to selectively shorten buffers

circe-display-images.el
Recent versions of emacs no longer use ImageMagick by default to display images: https://github.com/emacs-mirror/emacs/blob/emacs-27.1/etc/NEWS#L96-L98
Consequently, some emacs binary package maintainers are compiling emacs without ImageMagick support.
For example, on Arch Linux, notice how libmagick6 is listed as a dependency of an older version of emacs:
https://aur.archlinux.org/packages/emacs-24bit/
but not the latest emacs package:
https://www.archlinux.org/packages/extra/x86_64/emacs/
We can even see when libmagick was removed as a dependency:
https://github.com/archlinux/svntogit-packages/commit/f687dac70acd9a56279fbf0f8b34bf6a9865ba3b#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a 
This breaks circe-display-images on versions of emacs >= 27.1.
One could …
=> Makes ImageMagick image creation optional

irc.el
Sometimes it is necessary to override the certificate checks for a
given host. However this is only possible if the Network Security
Manager gets to verify the connection which it will not of gnutls
refused to complete the connection in the first place.
As a note for reference you can override nsm-temporary-host-settings
with something like:
(let ((id (nsm-id "irc.badcert.host" 6697)))
(setq nsm-temporary-host-settings
(list (list :id id :conditions '(:no-host-match :expired :invalid :verify-cert)))))
This follows the same format as nsm-permanent-host-settings which is
cached in ~/.emacs.d/network-security.data and is where things are set
interactively when using browsers like eww or gnus.
=> irc: defer to nsm to verify certificate errors

README.md, circe.el, irc.el
This PR adds support for:
- SASL EXTERNAL authentication method
A new option called `sasl-external` is provided. Setting it to a value
of true will enable external sasl authentication if the server supports
sasl.
- Authenticate with a client certificate when using TLS
A new option in called `tls-keylist` is provided. It's value is an alist
of (client key file, clent cert file) pairs as defined in
`gnutls-boot-parameters`. When specified the connection will be authenticated
with this client certificate.
Tested in Freenode and OFTC.
OFTC does not support sasl and Freenode allows SASL EXTERNAL though the client certificate authentication works without using it.
=> Add support for SASL EXTERNAL and TLS client certificates

tests/test-irc.el
The test was expecting `:verify-error t` but it's not longer passed to the `irc-connect` function.
=> Fix test `should call make-network-process if tls was requested`

circe.el, irc.el, tests/test-irc.el
This PR adds support for all the possible events sent during SASL
authentication:
- RPL_SASLSUCCESS
- ERR_SASLFAILED
- ERR_SASLTOOLONG
- ERR_SASLABORTED
- ERR_SASLALREADY
It also improves the registration logic in this way:
1. When using SASL on successful authentication the server will send 900 and
903. Right now on 900 the `sasl.login` event is always emitted even if we are
doing SASL authentication. This PR waits for the 903 when SASL negotiation is
ongoing. If SASL is not active the `sasl.login` will be emitted when 900 is
sent.
2. Right now the `CAP END` command is sent right after the `AUTHENTICATION` has
been sent without waiting for a response from the server. This PR also delays
the `CAP END` until we know the status of the SASL authentication (success,
failed or aborted).
3. It …
=> Improve the implementation of SASL authentication

circe.el
Add a new custom variable `circe-chat-buffer-name'. It supports two
expansions, {target} and {network}.
Remove the modification of `mode-line-buffer-identification' in chat-mode, the
full buffer name will be shown.
To go back to naming buffers only after the target, not the network, customise
`circe-chat-buffer-name' to "{target}".
=> Make the buffer-name customisable.

circe.el
With the recent irc split it makes sense to at least add it, and with the circumstances I feel it should probably be the default.
=> Add Libera Chat as default network

circe.el
The previous nickserv mask and challenge RE did not match correctly with the libera NOTICE, so automatic nickserv identification did not work. After analysing the raw output using `irc-debug-log`, I found that the RE I provided work (the challenge could be improved).
Feel free to ask questions or offer suggestions.
Best,
Aymeric
=> circe-network-defaults : correct libera nickserv mask and challenge

circe-new-day-notifier.el
Otherwise buffers show activity every day at midnight.
The format not being included in https://github.com/jorgenschaefer/circe/blob/d6f1fa18646f6ed2a1c0f06a4888130bd694ff19/circe.el#L459 is probably an oversight.
=> Don't track new days

circe.el
We currently have two ways to enable logging:
- globally, with `(enable-lui-logging-globally)`
- per buffer, with `M-x enable-lui-logging`
I believe we can make that a little easier and have an option
in `circe-network-option` to enable logging for a server:
```elisp
(setq circe-network-options '(
("Libera Chat"
;; ...
:logging t)))
```
Most of the time I want to enable or disable logging for a whole server.
I guess if people want to have more granular options, we can easily
support a list of channels there too.
If this gets merged, I'll update
https://github.com/jorgenschaefer/circe/wiki/Configuration#logging
=> Add a logging network option

circe-color-nicks.el
This extends `circe-color-nicks` to also work in `circe-query-mode` (a derived mode of `circe-chat-mode`, like `circe-channel-mode`): sometimes I miss the extra readability.
Do you want me to introduce a knob so people can keep the previous behavior of not colorizing nicks in queries?
=> Color nick in circe-query-mode

tests/test-tracking.el
Buttercup 1.34 requires `lexical-cast: t` in all files defining buttercup test suites for Emacs >= 29.
It was already documented as a requirement, but was only actually required for some specific functionality.  The introduction of Oclosures for Emacs versions that support them made it a hard requirement.
See also https://bugs.gentoo.org/926083 as reported in https://github.com/jorgenschaefer/emacs-buttercup/issues/243
=> Add lexical-cast to test-tracking.el

circe-pkg.el, circe.el
This pull-request moves metadata about this package from `<name>-pkg.el` to `<name>.el` and deletes the now redundant `<name>-pkg.el`.
The `<name>-pkg.el` file is not supposed to be tracked in the Git repository.  It is supposed to be *generated* by the package archive (e.g., MELPA) and *distributed* as part of the `<name>-<version>.tar` file.
*If you are already convinced, you can skip reading most of the rest, but please read the last page.*
----
Unfortunately the [Multi-file Packages](https://www.gnu.org/software/emacs/manual/html_node/elisp/Multi_002dfile-Packages.html) node in the info manual is not explicit about this.  So you may have read this:
> One of the files in the content directory must be named `NAME-pkg.el`.  It must contain a single Lisp form, consisting of a call to the …
=> Move metadata from circe-pkg.el to circe.el
